# Names the imported target of a dependency this package links, for the
# dependencies whose vcpkg config exports one.
#
# CMake de-duplicates link items by comparing targets against targets and
# paths against paths, never a target against a path. A raw archive path in
# this package's link interface therefore meets the very same archive named
# as an imported target by another package's config, and both reach the
# linker. Naming the target on this side makes the two one item.
#
# Only the target's name is stated here; where the archive lives, and which
# one a given configuration wants, remains the dependency's own business.
if(NOT COMMAND z_vcpkg_@PORT@_imported_target)
    function(z_vcpkg_@PORT@_imported_target out_var lib)
        set("${out_var}" "" PARENT_SCOPE)
        set(package "")
        set(find_args "")
        set(candidates "")
        if(lib MATCHES "^(z|zlib1?d?)$")
            set(package ZLIB)
            set(candidates ZLIB::ZLIB)
        elseif(lib MATCHES "^(lib)?png[0-9]*d?$")
            set(package PNG)
            set(candidates PNG::PNG)
        elseif(lib MATCHES "^(lib)?jpeg$")
            set(package JPEG)
            set(candidates JPEG::JPEG)
        elseif(lib MATCHES "^(lib)?turbojpeg$")
            set(package libjpeg-turbo)
            set(find_args CONFIG)
            set(candidates libjpeg-turbo::turbojpeg libjpeg-turbo::turbojpeg-static)
        elseif(lib MATCHES "^(lib)?expatw?(MD|MT)?d?$")
            set(package expat)
            set(find_args CONFIG)
            set(candidates expat::expat)
        elseif(lib MATCHES "^freetyped?$")
            set(package freetype)
            set(find_args CONFIG)
            set(candidates freetype)
        elseif(lib STREQUAL "harfbuzz")
            set(package harfbuzz)
            set(find_args CONFIG)
            set(candidates harfbuzz::harfbuzz)
        elseif(lib STREQUAL "harfbuzz-subset")
            set(package harfbuzz)
            set(find_args CONFIG)
            set(candidates harfbuzz::harfbuzz-subset)
        elseif(lib MATCHES "^icuucd?$")
            set(package ICU)
            set(find_args COMPONENTS uc)
            set(candidates ICU::uc)
        elseif(lib MATCHES "^icu(data|dt)d?$")
            set(package ICU)
            set(find_args COMPONENTS data)
            set(candidates ICU::data)
        elseif(lib MATCHES "^icu(i18n|in)d?$")
            set(package ICU)
            set(find_args COMPONENTS i18n)
            set(candidates ICU::i18n)
        elseif(lib STREQUAL "webp")
            set(package WebP)
            set(find_args CONFIG)
            set(candidates WebP::webp)
        elseif(lib STREQUAL "webpdecoder")
            set(package WebP)
            set(find_args CONFIG)
            set(candidates WebP::webpdecoder)
        elseif(lib STREQUAL "webpdemux")
            set(package WebP)
            set(find_args CONFIG)
            set(candidates WebP::webpdemux)
        elseif(lib MATCHES "^(lib)?webpmux$")
            set(package WebP)
            set(find_args CONFIG)
            set(candidates WebP::libwebpmux WebP::webpmux)
        elseif(lib STREQUAL "sharpyuv")
            set(package WebP)
            set(find_args CONFIG)
            set(candidates WebP::sharpyuv)
        elseif(lib MATCHES "^(lib)?avif$")
            set(package libavif)
            set(find_args CONFIG)
            set(candidates avif)
        elseif(lib MATCHES "^(lib)?yuv$")
            set(package libyuv)
            set(find_args CONFIG)
            set(candidates yuv)
        elseif(lib MATCHES "^(bz2|bzip2|libbz2)d?$")
            set(package BZip2)
            set(candidates BZip2::BZip2)
        elseif(lib MATCHES "^brotli(dec|enc|common)(-static)?$")
            string(REGEX REPLACE "^brotli(dec|enc|common).*$" "\\1" brotli_part "${lib}")
            set(package unofficial-brotli)
            set(find_args CONFIG)
            set(candidates "unofficial::brotli::brotli${brotli_part}")
        elseif(lib STREQUAL "fontconfig")
            set(package Fontconfig)
            set(candidates Fontconfig::Fontconfig)
        else()
            return()
        endif()
        foreach(candidate IN LISTS candidates)
            if(TARGET "${candidate}")
                set("${out_var}" "${candidate}" PARENT_SCOPE)
                return()
            endif()
        endforeach()
        find_package("${package}" QUIET ${find_args})
        foreach(candidate IN LISTS candidates)
            if(TARGET "${candidate}")
                set("${out_var}" "${candidate}" PARENT_SCOPE)
                return()
            endif()
        endforeach()
    endfunction()
endif()

if(NOT COMMAND z_vcpkg_@PORT@_get_link_libraries)
    function(z_vcpkg_@PORT@_get_link_libraries out_var type libraries)
        set(libs "")
        if(type STREQUAL "DEBUG")
            set(vcpkg_link_directories "${z_vcpkg_@PORT@_root}/debug/lib" "${z_vcpkg_@PORT@_root}/lib")
        else()
            set(vcpkg_link_directories "${z_vcpkg_@PORT@_root}/lib" "${z_vcpkg_@PORT@_root}/debug/lib")
        endif()
        foreach(lib IN LISTS libraries)
            if(lib MATCHES "^-framework ")
                # A bare "-framework Foo" is an opaque flag to CMake: it reaches
                # the link line unsplit, and only a driver that tokenizes it
                # itself will take it — swiftc rejects it. An absolute path to
                # the bundle is a framework CMake recognizes, so CMake writes
                # the spelling each driver wants ("-framework Foo" for clang,
                # "-Xlinker -framework -Xlinker Foo" for swiftc) and supplies
                # the search path itself.
                string(REGEX REPLACE "^-framework " "" framework "${lib}")
                string(MAKE_C_IDENTIFIER "${out_var}_framework_${framework}" framework_var)
                find_library("${framework_var}" NAMES "${framework}")
                mark_as_advanced("${framework_var}")
                if(${framework_var})
                    list(APPEND libs "${${framework_var}}")
                else()
                    list(APPEND libs "${lib}")
                endif()
            elseif(lib MATCHES [[^/|^(dl|m|pthread)$]])
                list(APPEND libs "${lib}")
            elseif(EXISTS "${lib}")
                list(APPEND libs "${lib}")
            else()
                z_vcpkg_@PORT@_imported_target(imported_target "${lib}")
                if(imported_target)
                    list(APPEND libs "${imported_target}")
                    continue()
                endif()
                string(MAKE_C_IDENTIFIER "${out_var}_${lib}_${type}" lib_var)
                find_library("${lib_var}" NAMES "${lib}" NAMES_PER_DIR PATHS ${vcpkg_link_directories})
                mark_as_advanced("${lib_var}")
                if(${lib_var})
                    list(APPEND libs "${${lib_var}}")
                else()
                    find_library("${lib_var}" NAMES "${lib}" NAMES_PER_DIR PATHS ${CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES} NO_DEFAULT_PATH)
                    if(${lib_var})
                        list(APPEND libs "${lib}")
                    else()
                        message(WARNING "Omitting '${lib}' from link libraries.")
                    endif()
                endif()
            endif()
        endforeach()
        set("${out_var}" "${libs}" PARENT_SCOPE)
    endfunction()
endif()

get_filename_component(z_vcpkg_@PORT@_root "${CMAKE_CURRENT_LIST_DIR}" PATH)
get_filename_component(z_vcpkg_@PORT@_root "${z_vcpkg_@PORT@_root}" PATH)

file(GLOB z_vcpkg_@PORT@_config_files "${CMAKE_CURRENT_LIST_DIR}/unofficial-@PORT@-*-targets.cmake")
foreach(z_vcpkg_@PORT@_config_file IN LISTS z_vcpkg_@PORT@_config_files)
    include("${z_vcpkg_@PORT@_config_file}")
endforeach()

unset(z_vcpkg_@PORT@_config_file)
unset(z_vcpkg_@PORT@_config_files)
unset(z_vcpkg_@PORT@_root)
